apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
  - ReadWriteMany
  selector:
    matchLabels:
      user: user09
      for: data
